name: Auto Tag

on:
  push:
    branches:
    - 'master'
    paths:
    - 'src/**'


jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: Create Tag
      uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: ${{ format('v{0}', github.run_number) }}
  release:
    needs: create_tag
    uses: ./.github/workflows/release.yml